### PR TITLE
fix(video): use component width to build video thumbnail

### LINKED ISSUE #7660: [Fix video poster sizes]: Across various components - DDS Consulting
**Engineering info:**  
- Innovation team engineer: @andy-blum 
- Innovation team JIRA Ticket: https://jsw.ibm.com/browse/HC-2351
- Carbon for IBM.com consulting engineer: @ariellalgilmore 
- Carbon for IBM.com estimate: 5
----

### Description

#7093 recently brought to light a resolution issue we're seeing with components leveraging the video service. It appears that we've [hard coded a value](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/4cf9bbc8de431ef63e3e10322db36580cd63446c/packages/web-components/src/components/cta/video-cta-composite.ts#L94) in some of our components leveraging this service. So it appears to be less of a problem with the video service and more of an issue with how our components are using the video service.

For instance, card in card (which spans 12 columns in most contexts at the moment) is trying to resize a `320px` (probably originally set to serve a card spanning 4 columns) image to `1152px` which is causing the pixelation our users are pointing out. I'd suggest we fix our components, and load images based on the correct size.

 

### Component(s) impacted

At a minimum it appears that the following components are directly impacted...

- [CTA card](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/CTA)
- [Video](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Video)

This leads to a larger downstream effect where the context is usually more stable but currently incorrect...

- [Content block segmented](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-block-segmented)
- [Content block simple](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-block-simple)
- [Content group simple](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-group-simple)
- [Content item horizontal](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-item-horizontal)
- [Content item](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-item)
- [Lead space block](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Lead-space-block)
- [Card section carousel](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-section-carousel)
- [Content item](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-item)
- [Feature section](Feature-section)
- [Card in card](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-in-card)

I tried to include all the related components that I could find, but it's possible this list isn't exhaustive and I missed a couple.

### Browser

Chrome

### Carbon for IBM.com version

1.27.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/

### Package

@carbon/ibmdotcom-react, @carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles, @carbon/ibmdotcom-services

### CodeSandbox example

https://www.ibm.com/standards/carbon/web-components/iframe.html?id=components-card-in-card--default&knob-video=true&knob-Image%20alt%20text%20(alt):=Image%20alt%20text&knob-Image%20src%20(defaultSrc):=3d9ceb3516be4517e20a044ca4722e6f.jpg&knob-Card%20Heading%20(heading):=Standard%20Bank%20Group%20prepares%20to%20embrace%20Africa%E2%80%99s%20AI%20opportunity&knob-Card%20Href%20(href):=https://example.com&knob-Card%20Eyebrow%20(eyebrow):=Label

### Steps to reproduce the issue (if applicable)

You can see the issue amplified in the [Card in card on storybook](https://www.ibm.com/standards/carbon/web-components/iframe.html?id=components-card-in-card--default&knob-video=true&knob-Image%20alt%20text%20(alt):=Image%20alt%20text&knob-Image%20src%20(defaultSrc):=3d9ceb3516be4517e20a044ca4722e6f.jpg&knob-Card%20Heading%20(heading):=Standard%20Bank%20Group%20prepares%20to%20embrace%20Africa%E2%80%99s%20AI%20opportunity&knob-Card%20Href%20(href):=https://example.com&knob-Card%20Eyebrow%20(eyebrow):=Label).

###### What is now (blurry)

image

###### What is should be (sharp)

image

### Release date (if applicable)

_No response_

### Additional Information
- Avoid introducing any new props that would allow the author to change the poster sizes within the components.
- Engineering should review the Visual specs to endure capturing the poster size within the component
- Kaltura Video Thumbnail API: https://developer.kaltura.com/api-docs/Engage_and_Publish/kaltura-thumbnail-api.html 
- [Video service func specs](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Video-service)
- [API info](https://ibmdotcom-services.mybluemix.net/KalturaPlayerAPI.html)
- Functional specs issue (#7187)
- Visual QA testing issue (#7229)
- Prod QA testing issue (#7230)

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

Fixes #7660

### Description

This PR addresses video poster sizes in two different places.

1) In the video-cta-composite component, we use the component's width to build the kaltura thumbnail URL.
2) In the video-player-composite component, that's not possible, so we hardcode a small value of `3` during the page load, and then use an event callback to replace the small image with the full-sized one which uses the component width in the URL

2 has the side effect of loading 2 images, so we minimize the first one by making it a 3px wide image. This gets so pixelated that to the end user it simply looks like a gradient that matches the color scheme of the final poster

Initial load:
Screen Shot 2021-12-21 at 3 52 39 PM

Post-load callback:
Screen Shot 2021-12-21 at 3 52 19 PM

### Changelog

**Changed**

- Video posters are built to the width of the component they'll need to cover

### CODE REVIEW

**Comment by proeung** [comment]
@andy-blum I'm not seeing these changes implemented on the React package side. Can you take a look? Also, happy to break this issue (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7660) into two parts if the React one needed some discussion/consulting time.

File: packages/react/src/components/CTA/CardCTA.js [hunk 1]
```diff
@@ -28,6 +28,14 @@ const CardCTA = ({
   // eslint-disable-next-line no-unused-vars
   const { style, ...cardProps } = otherProps;
 
+  const [thumbnailSize, setThumbnailSize] = useState(3);
+
+  const refImage = useCallback(node => {
+    if (node && node.parentElement) {
```
Comment (emyarod) [inline packages/react/src/components/CTA/CardCTA.js:34]:
```suggestion
    if (node?.parentElement) {
```

I think we can chain these together

File: packages/react/src/components/VideoPlayer/VideoImageOverlay.js [hunk 2]
```diff
@@ -26,6 +26,14 @@ const VideoImageOverlay = ({
   thumbnail,
   ...rest
 }) => {
+  const [thumbnailSize, setThumbnailSize] = useState(3);
+
+  const refImage = useCallback(node => {
+    if (node && node.parentElement) {
```
Comment (emyarod) [inline packages/react/src/components/VideoPlayer/VideoImageOverlay.js:32]:
```suggestion
    if (node?.parentElement) {
```

File: packages/web-components/src/components/cta/video-cta-composite.ts [hunk 3]
```diff
@@ -91,7 +91,7 @@ class DDSVideoCTAComposite extends ModalRenderMixin(HostListenerMixin(LitElement
     const { href, videoName: customVideoName, videoDescription } = event.detail;
     (event.target as VideoCTAMixinImpl).videoThumbnailUrl = KalturaPlayerAPI.getThumbnailUrl({
       mediaId: href,
-      width: '320',
+      width: event.target.offsetWidth,
```
Comment (emyarod) [inline packages/web-components/src/components/cta/video-cta-composite.ts:94]:
```suggestion
      width: event?.target?.offsetWidth,
```

it looks like this is causing a test failure since it may be `null`

**Review by emyarod — COMMENTED** [review]
looks good to me

it looks like snapshots need to updated again to pass CI

**Comment by proeung** [comment]
@andy-blum Thanks for fixing the video poster sizes on the React package!

@oliviaflory or @RichKummer Can we get a design QA for this PR as well? Thanks!

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Review by RichKummer — APPROVED** [review]
Looks good! Thanks @andy-blum!
