### PR TITLE
fix(data table): filter issue in expansion table

### LINKED ISSUE #11179: Unable to filter inside a expandable fields
### Description

In a cds-table-expanded-row component, I have specific text that I want to be able to filter, but the filterRows function doesn't work for me because it only returns the content of the row and not the expanded text.

### Component(s) impacted

```
<cds-table>
<cds-table-expanded-row></cds-table-expanded-row>
</cds-table>

```

### Browser

Chrome

### Carbon for IBM.com version

v2

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

private site

### Package

@carbon/web-components

### CodeSandbox example

https://codesandbox.io/p/devbox/priceless-cache-gtz44y?file=%2Findex.html

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by sangeethababu9223**
### Related Ticket(s)

Closes #11179

### Description

For expansion table, filtering doesn't include the content in the expanded row.

### Changelog

**Changed**

- Updated the filter function to check the expanded row.

### CODE REVIEW

File: packages/carbon-web-components/src/components/data-table/table.ts [hunk 1]
```diff
@@ -236,10 +236,17 @@ class CDSTable extends HostListenerMixin(LitElement) {
   private _handleFilterRows() {
     const unfilteredRows = [] as any;
     forEach(this._tableRows, (elem) => {
-      const rowText = elem.textContent?.trim();
-      const filtered = this.filterRows(rowText as string, this._searchValue);
+      let rowText = elem.textContent?.trim();
+      let filtered = this.filterRows(rowText as string, this._searchValue);
+      console.log('filtered', filtered);
```
Comment (IgnacioBecerra) [inline packages/carbon-web-components/src/components/data-table/table.ts:241]:
```suggestion
```

**Review by IgnacioBecerra — APPROVED** [review]
LGTM! Thanks @sangeethababu9223!

File: packages/carbon-web-components/src/components/data-table/table.ts (hunk 1 above)
Comment (sangeethababu9223) [reply packages/carbon-web-components/src/components/data-table/table.ts]: Thanks @IgnacioBecerra.
log is removed.
