### PR TITLE
fix(masthead-l1): fix focusout logic

### LINKED ISSUE #10521: [Masthead v2 L1]: Clicking empty space in dropdown causes dropdown to close
### Description

JIRA: https://jsw.ibm.com/browse/ADCMS-3371

Screenshot 2023-05-30 at 10 40 45 AM

### Component(s) impacted

Masthead v2 L1

### Browser

_No response_

### Carbon for IBM.com version

masthead-v2-dev

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

ibm.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://ibm.com/products/turbonomic

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

Closes #10521

### Description

Previous logic used only `Node.compareDocumentPosition()` and closed if the `currentTarget` did not contain `relatedTarget`. This forgot to account for `currentTarget === relatedTarget`.

### Changelog

**Changed**

- fixed focusout handler bug in masthead L1

### CODE REVIEW

File: packages/web-components/src/components/masthead/masthead-l1.ts [hunk 1]
```diff
@@ -60,19 +60,25 @@ function handleDropdownClose(event: FocusEvent | KeyboardEvent) {
       }
       case 'focusout': {
         const { relatedTarget } = event as FocusEvent;
```
Comment (pjudge) [inline packages/web-components/src/components/masthead/masthead-l1.ts:62]: is this syntax related to this? https://stackoverflow.com/a/33798750

File: packages/web-components/src/components/masthead/masthead-l1.ts [hunk 2]
```diff
@@ -60,19 +60,25 @@ function handleDropdownClose(event: FocusEvent | KeyboardEvent) {
...
-        if (
-          !relatedTarget ||
-          !currentTarget ||
-          !(
-            (relatedTarget as Node).compareDocumentPosition(
-              currentTarget as Node
-            ) & 8
-          )
-        ) {
+        const hasUnknownTargets = !relatedTarget || !currentTarget;
```
Comment (pjudge) [inline packages/web-components/src/components/masthead/masthead-l1.ts:63]: this is saying `hasUnknownTargets` is literally everything except `relatedTarget` or `currentTarget`?

Comment (pjudge) [reply packages/web-components/src/components/masthead/masthead-l1.ts:63]: Or is this a boolean...?

File: packages/web-components/src/components/masthead/masthead-l1.ts (hunk 1 above)
Comment (andy-blum) [reply packages/web-components/src/components/masthead/masthead-l1.ts:62]: Yep, this is [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment). While it's not any more efficient when you need a single item, it's super handy when you need to pull a bunch of stuff out at once. For example:

```
const {
  relatedTarget,
  currentTarget,
  type
} = event;
```

File: packages/web-components/src/components/masthead/masthead-l1.ts (hunk 2 above)
Comment (andy-blum) [reply packages/web-components/src/components/masthead/masthead-l1.ts:63]: In [FocusEvents](https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent) there is a `currentTarget` property which points to the element that _triggered_ the event. This is the element that lost focus in `focusout` events and the one that gained focus on `focusin` events.

They also have a special `relatedTarget` property that points to the "other" element in the equation.

In `focusout` events, focus leaves `currentTarget` and goes to `relatedTarget`.

In `focusin` events, focus leaves `relatedTarget` and goes to `currentTarget`.

The `hasUnknownTargets` variable here is a boolean that checks if either is falsy. The most common case for this is someone has navigated away from the page. In this case, focus has left the dropdown and gone to `undefined`.

File: packages/web-components/src/components/masthead/masthead-l1.ts [hunk 3]
```diff
@@ -60,19 +60,25 @@ function handleDropdownClose(event: FocusEvent | KeyboardEvent) {
...
+
+        if (!hasUnknownTargets) {
+          const comparison = (relatedTarget as Node).compareDocumentPosition(
+            currentTarget as Node
+          );
+
+          focusHasEscaped =
+            !(comparison & 8) && // relatedTarget is not ancestor of currentTarget
+            relatedTarget !== currentTarget;
+        }
```
[the remark this answers is not in the document]
Comment (andy-blum) [reply packages/web-components/src/components/masthead/masthead-l1.ts:74]: `Node.compareDocumentPosition` returns a bitmask, which was a new thing to me in this project as well. See [the article](https://www.lullabot.com/articles/bitmasks-javascript-computer-science-crash-course) I wrote about it.

Essentially, we're checking if the element that has focus is inside the DOM subtree of the `li` we're watching for `focusout`. If focus is still _inside_ the `li` element, we don't want to close.

`focusHasEscaped` will evaluate to true if focus is not in the subtree or in the top-level of the dropdown
