### PR TITLE
fix(dotcom-shell): accessibility issue with dotcom shell

### LINKED ISSUE #9036: [accessibility]: accessibility issue with dotshell
### Description

I am using the dotshell example to start
and i have some violations when using the IBM Equal Access Accessibility Checker
[Accessibility_Report-IBM Terms(10).xlsx](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/files/8976875/Accessibility_Report-IBM.Terms.10.xlsx)
r

image

### Component(s) impacted

https://wwwstage.ibm.com/support/customer/csol/terms/carbon/index-dotshell.html

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon for IBM.com version

v1.35.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

https://wwwstage.ibm.com/support/customer/csol/terms/carbon/index-dotshell.html

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://wwwstage.ibm.com/support/customer/csol/terms/carbon/index-dotshell.html

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by sangeethababu9223**
### Related Ticket(s)

Closes #9036 

### Description

accessibility issue with dotcom shell. 
Most of the items listed  in the issue are no longer showing. 

### Changelog

**New**

- Added aria-label for Legal Navigation

### CODE REVIEW

File: packages/web-components/src/components/footer/legal-nav.ts [hunk 1]
```diff
@@ -69,7 +69,7 @@ class DDSLegalNav extends StableSelectorMixin(LitElement) {
 
   render() {
     return html`
-      <nav class="${prefix}--legal-nav">
+      <nav class="${prefix}--legal-nav" aria-label="Legal Navigation">
```
Comment (IgnacioBecerra) [inline packages/web-components/src/components/footer/legal-nav.ts:72]: This is good, but it would be better by allowing the user to set this, mainly to accommodate for translations. You could make a property to make this easier for the adopter.

Comment (sangeethababu9223) [reply packages/web-components/src/components/footer/legal-nav.ts]: Added the aria label as property. 
Thanks

**Review by kennylam — APPROVED** [review]
LGTM!

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by IgnacioBecerra — APPROVED** [review]
