### PR TITLE
fix(table-of-contents): compensate for masthead on scroll up

### LINKED ISSUE #6463: [Table of contents] horizontal TOC overlapping content - DDS consulting - AEM dev to fix
## Detailed description

We're seeing that the horizontal TOC properly attaches to the masthead as you scroll down the page but it the height of the masthead and the TOC navigation causes it to overlap the content within the page.

ADCMS-1392

## Steps to reproduce the issue

1. Create a page with a masthead and a horizontal table of contents.
2. Click on the items of the TOC to scroll down the page

### PR DESCRIPTION
**Pull request by andy-blum**
### Related Ticket(s)

[[Table of contents] horizontal TOC overlapping content - DDS consulting - AEM dev to fix #6463](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6463)

### Description

When used in combination with the masthead, navigating up the page with the horizontal table of contents results in the target to be overlapped slightly

### Changelog

**Changed**

- horizontal table-of-contents component compensates 48px for the height of the masthead when scrolling the page upwards

### CODE REVIEW

File: packages/web-components/src/components/table-of-contents/table-of-contents.ts [hunk 1]
```diff
@@ -306,8 +306,20 @@ class DDSTableOfContents extends HostListenerMixin(StableSelectorMixin(LitElemen
    */
   private _handleUserInitiatedJump(target: string) {
     const elem = this.querySelector(`a[name="${target}"]`);
-    elem?.scrollIntoView();
-    if (elem) {
+    const masthead = this.ownerDocument.querySelector('dds-masthead');
```
Comment (ariellalgilmore) [inline packages/web-components/src/components/table-of-contents/table-of-contents.ts:309]: Thanks for this PR!! Looks great. Just a 1 minor comment besides changing the prefix. Instead of using `48` we need to account for the masthead L1 being visible as well, so possibly creating a `mastheadHeight` variable and using `masthead` to get the `offsetHeight` to replace the `48`. 

```suggestion
    const masthead = this.ownerDocument.querySelector('${ddsPrefix}-masthead');
```

Comment (ariellalgilmore) [reply packages/web-components/src/components/table-of-contents/table-of-contents.ts]: This looks great!! Thanks for the updates :)

**Review by ariellalgilmore — APPROVED** [review]
